### ISSUE TITLE
Error in parsing sample_unix.hl7

### ISSUE THREAD

**Issue by kesavkolla** [LinuxForHealth/hl7v2-fhir-converter#48]
I tried to parse the sample_unix.hl7 which is included in the source code. That also has show many warnings.

```
2020-11-17 23:56:18.889  WARN 1025953 --- [           main] ca.uhn.fhir.parser.LenientErrorHandler   : Found incorrect type for element coding - Expected ARRAY and found OBJECT
2020-11-17 23:56:18.890  WARN 1025953 --- [           main] ca.uhn.fhir.parser.LenientErrorHandler   : Found incorrect type for element coding - Expected ARRAY and found OBJECT
2020-11-17 23:56:18.894  WARN 1025953 --- [           main] i.g.l.hl7.parsing.HL7DataExtractor       : Failure in checking if segment exsts: PV2

java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at ca.uhn.hl7v2.model.Unmodifiable$UnmodifiableGroup.get(Unmodifiable.java:298) ~[hapi-base-2.3.jar:na]
	at ca.uhn.hl7v2.model.Unmodifiable$UnmodifiableGroup.get(Unmodifiable.java:285) ~[hapi-base-2.3.jar:na]
	at io.github.linuxforhealth.hl7.parsing.HL7DataExtractor.doesSegmentExists(HL7DataExtractor.java:143) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.parsing.HL7DataExtractor.getAllStructures(HL7DataExtractor.java:198) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.message.util.SegmentExtractorUtil.extractAdditionalSegmentValue(SegmentExtractorUtil.java:163) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.message.util.SegmentExtractorUtil.extractSegmentGroup(SegmentExtractorUtil.java:258) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.message.HL7MessageEngine.generateSingle(HL7MessageEngine.java:198) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.message.HL7MessageEngine.transform(HL7MessageEngine.java:112) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.message.HL7MessageModel.convert(HL7MessageModel.java:75) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.HL7ToFHIRConverter.convert(HL7ToFHIRConverter.java:128) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.HL7ToFHIRConverter.convert(HL7ToFHIRConverter.java:87) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at com.e314.hl7.Hl7Application.run(Hl7Application.java:29) ~[classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804) ~[spring-boot-2.4.0.jar:2.4.0]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:788) ~[spring-boot-2.4.0.jar:2.4.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:333) ~[spring-boot-2.4.0.jar:2.4.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309) ~[spring-boot-2.4.0.jar:2.4.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298) ~[spring-boot-2.4.0.jar:2.4.0]
	at com.e314.hl7.Hl7Application.main(Hl7Application.java:22) ~[classes/:na]

2020-11-17 23:56:18.920  WARN 1025953 --- [           main] i.g.l.hl7.data.date.DateUtil             : Date parsing error for instant 2014-09-12T22:00:00

java.time.format.DateTimeParseException: Text '2014-09-12T22:00:00' could not be parsed at index 19
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2046) ~[na:na]
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1948) ~[na:na]
	at java.base/java.time.Instant.parse(Instant.java:395) ~[na:na]
	at io.github.linuxforhealth.hl7.data.date.DateUtil.getTemporal(DateUtil.java:145) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.data.Hl7RelatedGeneralUtils.diffDateMin(Hl7RelatedGeneralUtils.java:103) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.apache.commons.jexl3.internal.introspection.MethodExecutor.invoke(MethodExecutor.java:93) ~[commons-jexl3-3.1.jar:3.1]
	at org.apache.commons.jexl3.internal.Interpreter.call(Interpreter.java:1598) ~[commons-jexl3-3.1.jar:3.1]
	at org.apache.commons.jexl3.internal.Interpreter.visit(Interpreter.java:1306) ~[commons-jexl3-3.1.jar:3.1]
	at org.apache.commons.jexl3.parser.ASTMethodNode.jjtAccept(ASTMethodNode.java:18) ~[commons-jexl3-3.1.jar:3.1]
	at org.apache.commons.jexl3.internal.Interpreter.visit(Interpreter.java:1018) ~[commons-jexl3-3.1.jar:3.1]
	at org.apache.commons.jexl3.parser.ASTReference.jjtAccept(ASTReference.java:18) ~[commons-jexl3-3.1.jar:3.1]
	at org.apache.commons.jexl3.internal.Interpreter.visit(Interpreter.java:892) ~[commons-jexl3-3.1.jar:3.1]
	at org.apache.commons.jexl3.parser.ASTJexlScript.jjtAccept(ASTJexlScript.java:55) ~[commons-jexl3-3.1.jar:3.1]
	at org.apache.commons.jexl3.internal.Interpreter.interpret(Interpreter.java:186) ~[commons-jexl3-3.1.jar:3.1]
	at org.apache.commons.jexl3.internal.Script.execute(Script.java:178) ~[commons-jexl3-3.1.jar:3.1]
	at org.apache.commons.jexl3.internal.Script.evaluate(Script.java:170) ~[commons-jexl3-3.1.jar:3.1]
	at io.github.linuxforhealth.core.data.JexlEngineUtil.evaluate(JexlEngineUtil.java:76) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.message.HL7MessageData.evaluateJexlExpression(HL7MessageData.java:165) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.expression.JELXExpression.evaluateExpression(JELXExpression.java:80) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.expression.AbstractExpression.generateValue(AbstractExpression.java:264) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.expression.AbstractExpression.evaluateSingle(AbstractExpression.java:183) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.expression.AbstractExpression.evaluate(AbstractExpression.java:148) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.resource.HL7DataBasedResourceModel.executeExpression(HL7DataBasedResourceModel.java:240) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.resource.HL7DataBasedResourceModel.evaluate(HL7DataBasedResourceModel.java:143) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.expression.ResourceExpression.evaluateExpression(ResourceExpression.java:105) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.expression.AbstractExpression.generateValue(AbstractExpression.java:264) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.expression.AbstractExpression.evaluateSingle(AbstractExpression.java:183) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.expression.AbstractExpression.evaluate(AbstractExpression.java:148) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.resource.HL7DataBasedResourceModel.evaluateResourceExpression(HL7DataBasedResourceModel.java:217) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.resource.HL7DataBasedResourceModel.evaluate(HL7DataBasedResourceModel.java:131) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.message.HL7MessageEngine.generateSingle(HL7MessageEngine.java:212) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.message.HL7MessageEngine.transform(HL7MessageEngine.java:112) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.message.HL7MessageModel.convert(HL7MessageModel.java:75) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.HL7ToFHIRConverter.convert(HL7ToFHIRConverter.java:128) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.HL7ToFHIRConverter.convert(HL7ToFHIRConverter.java:87) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at com.e314.hl7.Hl7Application.run(Hl7Application.java:29) ~[classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804) ~[spring-boot-2.4.0.jar:2.4.0]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:788) ~[spring-boot-2.4.0.jar:2.4.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:333) ~[spring-boot-2.4.0.jar:2.4.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309) ~[spring-boot-2.4.0.jar:2.4.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298) ~[spring-boot-2.4.0.jar:2.4.0]
	at com.e314.hl7.Hl7Application.main(Hl7Application.java:22) ~[classes/:na]

2020-11-17 23:56:18.922  WARN 1025953 --- [           main] i.g.l.hl7.data.date.DateUtil             : Date parsing error for ZonedDateTime 2014-09-12T22:00:00

java.time.format.DateTimeParseException: Text '2014-09-12T22:00:00' could not be parsed at index 19
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2046) ~[na:na]
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1948) ~[na:na]
	at java.base/java.time.ZonedDateTime.parse(ZonedDateTime.java:598) ~[na:na]
	at io.github.linuxforhealth.hl7.data.date.DateUtil.getTemporal(DateUtil.java:152) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.data.Hl7RelatedGeneralUtils.diffDateMin(Hl7RelatedGeneralUtils.java:103) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.apache.commons.jexl3.internal.introspection.MethodExecutor.invoke(MethodExecutor.java:93) ~[commons-jexl3-3.1.jar:3.1]
	at org.apache.commons.jexl3.internal.Interpreter.call(Interpreter.java:1598) ~[commons-jexl3-3.1.jar:3.1]
	at org.apache.commons.jexl3.internal.Interpreter.visit(Interpreter.java:1306) ~[commons-jexl3-3.1.jar:3.1]
	at org.apache.commons.jexl3.parser.ASTMethodNode.jjtAccept(ASTMethodNode.java:18) ~[commons-jexl3-3.1.jar:3.1]
	at org.apache.commons.jexl3.internal.Interpreter.visit(Interpreter.java:1018) ~[commons-jexl3-3.1.jar:3.1]
	at org.apache.commons.jexl3.parser.ASTReference.jjtAccept(ASTReference.java:18) ~[commons-jexl3-3.1.jar:3.1]
	at org.apache.commons.jexl3.internal.Interpreter.visit(Interpreter.java:892) ~[commons-jexl3-3.1.jar:3.1]
	at org.apache.commons.jexl3.parser.ASTJexlScript.jjtAccept(ASTJexlScript.java:55) ~[commons-jexl3-3.1.jar:3.1]
	at org.apache.commons.jexl3.internal.Interpreter.interpret(Interpreter.java:186) ~[commons-jexl3-3.1.jar:3.1]
	at org.apache.commons.jexl3.internal.Script.execute(Script.java:178) ~[commons-jexl3-3.1.jar:3.1]
	at org.apache.commons.jexl3.internal.Script.evaluate(Script.java:170) ~[commons-jexl3-3.1.jar:3.1]
	at io.github.linuxforhealth.core.data.JexlEngineUtil.evaluate(JexlEngineUtil.java:76) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.message.HL7MessageData.evaluateJexlExpression(HL7MessageData.java:165) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.expression.JELXExpression.evaluateExpression(JELXExpression.java:80) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.expression.AbstractExpression.generateValue(AbstractExpression.java:264) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.expression.AbstractExpression.evaluateSingle(AbstractExpression.java:183) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.expression.AbstractExpression.evaluate(AbstractExpression.java:148) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.resource.HL7DataBasedResourceModel.executeExpression(HL7DataBasedResourceModel.java:240) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.resource.HL7DataBasedResourceModel.evaluate(HL7DataBasedResourceModel.java:143) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.expression.ResourceExpression.evaluateExpression(ResourceExpression.java:105) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.expression.AbstractExpression.generateValue(AbstractExpression.java:264) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.expression.AbstractExpression.evaluateSingle(AbstractExpression.java:183) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.expression.AbstractExpression.evaluate(AbstractExpression.java:148) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.resource.HL7DataBasedResourceModel.evaluateResourceExpression(HL7DataBasedResourceModel.java:217) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.resource.HL7DataBasedResourceModel.evaluate(HL7DataBasedResourceModel.java:131) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.message.HL7MessageEngine.generateSingle(HL7MessageEngine.java:212) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.message.HL7MessageEngine.transform(HL7MessageEngine.java:112) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.message.HL7MessageModel.convert(HL7MessageModel.java:75) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.HL7ToFHIRConverter.convert(HL7ToFHIRConverter.java:128) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.HL7ToFHIRConverter.convert(HL7ToFHIRConverter.java:87) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at com.e314.hl7.Hl7Application.run(Hl7Application.java:29) ~[classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804) ~[spring-boot-2.4.0.jar:2.4.0]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:788) ~[spring-boot-2.4.0.jar:2.4.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:333) ~[spring-boot-2.4.0.jar:2.4.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309) ~[spring-boot-2.4.0.jar:2.4.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298) ~[spring-boot-2.4.0.jar:2.4.0]
	at com.e314.hl7.Hl7Application.main(Hl7Application.java:22) ~[classes/:na]

2020-11-17 23:56:19.327  WARN 1025953 --- [           main] ca.uhn.fhir.parser.LenientErrorHandler   : Found incorrect type for element coding - Expected ARRAY and found OBJECT
2020-11-17 23:56:19.328  WARN 1025953 --- [           main] ca.uhn.fhir.parser.LenientErrorHandler   : Found incorrect type for element coding - Expected ARRAY and found OBJECT
2020-11-17 23:56:19.353 ERROR 1025953 --- [           main] i.g.l.hl7.parsing.HL7DataExtractor       : HL7 String OBR-22Can't find OBR as a direct child  
2020-11-17 23:56:19.361  WARN 1025953 --- [           main] ca.uhn.fhir.parser.LenientErrorHandler   : Found incorrect type for element reaction - Expected ARRAY and found OBJECT
2020-11-17 23:56:19.364  WARN 1025953 --- [           main] ca.uhn.fhir.parser.LenientErrorHandler   : Found incorrect type for element reaction - Expected ARRAY and found OBJECT
```

**Comment by dixonwhitmire** [comment]
It may be worthwhile to review the sample data to see if we can update the fields in question, so that the warnings do not occur.

**Comment by kesavkolla** [comment]
Date parsing warning seems incorrect. The date in the message is a valid HL7 date. Still the parser throwing error. I think the code is using Instant to parse which is expecting zone information. The code should use localdate to parse the dates.

**Comment by pbhallam** [comment]
@kesavkolla -- The issue with Date parsing is not about date being invalid. The issue is that for a certain field in FHIR model, I need to determine the diff of two dates. 

java.time.format.DateTimeParseException: Text '2014-09-12T22:00:00' could not be parsed at index 19
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2046) ~[na:na]
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1948) ~[na:na]
	at java.base/java.time.ZonedDateTime.parse(ZonedDateTime.java:598) ~[na:na]
	at io.github.linuxforhealth.hl7.data.date.DateUtil.getTemporal(DateUtil.java:152) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]
	at io.github.linuxforhealth.hl7.data.Hl7RelatedGeneralUtils.**diffDateMin**(Hl7RelatedGeneralUtils.java:103) ~[hl7v2-fhir-converter-1.0.3-alpha.jar:na]

And when I diff the date I am expecting both the dates to have zone information or else I return a null value. 
So when ever this request happens and the dates (mostly start and end dates) do not have zone information then this warning is thrown. Right now its more of a noice.  
Another option is to check if both dates do not have zone information then assume that they are for the same timezone and do a LocalDateTime diff.

**Comment by kesavkolla** [comment]
In that case may the message should not be a warning. It basically gives wrong impression to the user

**Comment by pbhallam** [comment]
@kesavkolla  -- I agree its bit misleading. I need to fix the logging issue here.

**Comment by pbhallam** [comment]
Fix: https://github.com/LinuxForHealth/hl7v2-fhir-converter/pull/54
